[project]
name = "mcp-server-time"
version = "0.1.0"
description = "A Model Context Protocol server providing tools for time queries and timezone conversions for LLMs"
readme = "README.md"
requires-python = ">=3.10"
authors = []
keywords = []
license = { text = "MIT" }
classifiers = []
dependencies = [
    "fastmcp==3.0.0rc2",
    "pydantic>=2.0.0",
    "tzdata>=2024.2",
    "tzlocal>=5.3.1",
]

[project.scripts]
mcp-server-time = "mcp_server_time:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
